### ISSUE TITLE
Consider to make JsonApiModel class public

### ISSUE THREAD

**Issue by peter-plochan** [toedter/spring-hateoas-jsonapi#20]
Now, the [JsonApiModel class](https://github.com/toedter/spring-hateoas-jsonapi/blob/c60a64f6b10e72091a83a530fe3bc48a666b157d/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/JsonApiModel.java#L31) is `package-private`. Consider to make it `public` which e.g. (in our case) enables possibility to test outputs from specific [JsonApiModelBuilder](https://github.com/toedter/spring-hateoas-jsonapi/blob/master/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/JsonApiModelBuilder.java) builds.

**Comment by toedter** [comment]
Thanks for pointing this out. We had discussions about that topic in the Spring HATEOAS community. The issue here is that users then expose specific representation model implementations that only make sense for specific media types.  For example, an endpoint could return `ResponseEntity<JsonApiModel>` which would break the media type independent approach of Spring HATEOAS when it comes to API.

If you want to provide JSON:API only, this might make sense but if you want to accept different media types it would make the API more complicated. I will restart the discussion again, but I would like to stay with the generic Spring HATEOAS model on the REST endpoint API side.

For testing purposes, you could provide something like:

``` Java
        @Bean
        JsonApiConfiguration jsonApiConfiguration() {
            return new JsonApiConfiguration()
                    .withObjectMapperCustomizer(objectMapper -> {
                        yourStaticTestObjectMapper = objectMapper;
                    });
        }

```

and then use `yourStaticTestObjectMapper ` for serializing the result of the specific JsonApiModelBuilder builds in your tests.

**Comment by peter-plochan** [comment]
Hi @toedter, thanks for quick response. Actually, the problem is that we use custom `RepresentationModelAssembler` for being able to serialize our specific entity model to different media types (along with JSON:API), so we are somehow building `JsonApiModel` within this assembler. We want to run **regular unit tests** against this assembler, so we don't want to pointlessly initialize the whole Spring context for just being able to check if returning `RepresentationModel` structure is a correct JSON:API model.

**Comment by toedter** [comment]
I see your point, but I will stick with the Spring HATEOAS approach to only having the generic `RepresentationModel ` classes public. A workaround for your use case would be to create a TestWrapper class in a package `com.toedter.spring.hateoas.jsonapi`. There you could cast a `RepresentationModel ` to a `JsonApiModel `and get the data for your test.
