### ISSUE TITLE
Support for @JsonApiType on class level

### ISSUE THREAD

**Issue by marceloverdijk** [toedter/spring-hateoas-jsonapi#6]
Would it be possible to instead of:

```
@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
@With
public class MovieWithDirectors extends Movie {
    @JsonApiType
    String myType = "movies";
``` 

also support:

```
@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
@With
@JsonApiType("movies"")
public class MovieWithDirectors extends Movie {
```

**Comment by toedter** [comment]
Hi Marcel,

thanks for the suggestion.
Yes, it would be possible. I'll think about it.
Today, you could already use the JsonApiConfiguration to specify a JSON:API type for any Java class, like

```
@Bean
JsonApiConfiguration jsonApiConfiguration() {
    return new JsonApiConfiguration()
            .withTypeForClass(MovieWithDirectors .class, "movies");
}

```

Then you would not need a type attribute in the MovieWithDirectors class at all.
I chose this solution over a class annotation because you could apply the configuration any class, including your own.

Would this be good enough for you or would you think a class-based annotation provides additional benefits or is more convenient compared with the configuration?

**Comment by marceloverdijk** [comment]
Personally I think in class level is more convenient as there the other annotations are defined as well and the properties itself.

**Comment by toedter** [comment]
Good point. I'll see what I can do.

**Comment by toedter** [comment]
I started this but experienced the following issue: A class-level annotation would need a mandatory value that must not have a default value (e.g. `@JsonApiType("movies")`) but the filed- and method-level annotation must NOT have a value, because the value of the attribute is taken at runtime. So a solution would be to create a new annotation with a different name, but I don't like this too much because the purpose of these 2 annotations would be the same and it would be hard for the users to figure out when to use which.

This is harder than expected.

**Comment by marceloverdijk** [comment]
Maybe `""` as default value?

**Comment by toedter** [comment]
I decided type safety is more important, so I introduced a new class level annotation like:

```
@JsonApiTypeForClass("my-movies")
public class Movie5 extends Movie {

```

**Comment by metacubed** [comment]
@toedter one other suggestion is:

- For classes: `@JsonApiType` with a mandatory parameter
- For methods/fields: `@JsonApiTypeMarker` without a parameter

In the first case, you are actually providing/specifying the type information.
In the second case, you are only indicating (marking) where you can get the type information.

This is a breaking change, but hope that's ok because the version is not 1.0.

**Comment by toedter** [comment]
@metacubed, thanks for the suggestion, naming is a very difficult thing but I try not to introduce breaking changes right now.
That's why I kept the original `@JsonApiType` and introduced `@JsonApiTypeForClass`. 

I agree that the current naming is not optimal, but I think that `@JsonApiTypeMarker` is also not optimal, since most annotations are markers. Maybe in a later version, when the API gets more mature, I will reconsider your suggestion.

**Comment by metacubed** [comment]
No problem, it was just a suggestion. Thank you for the great library!
