### ISSUE TITLE
Automatic-Module-Name

### ISSUE THREAD

**Issue by golabk** [toedter/spring-hateoas-jsonapi#79]
Hello,

Can you add Automatic-Module-Name to the MANIFEST.MF so that it can be used in module-info.java

**Comment by toedter** [comment]
Thx for the hint, I added a more verbose manifest:

Manifest-Version: 1.0
Build-Timestamp: 2023-08-11T06:33:27.903+0000
Created-By: Gradle 8.2.1
Build-Jdk: 17.0.8 (Azul Systems, Inc. 17.0.8+7-LTS)
Build-OS: Linux amd64 5.15.0-1042-azure
Implementation-Title: JSON:API for Spring HATEOAS
Implementation-Version: 2.0.6-SNAPSHOT
Automatic-Module-Name: spring.hateoas.jsonapi

The Automatic-Module-Name is the same as if where no entry in the manifest since it is derived by the JAR name if no manifest entry is available. 

It is in the current snapshot and will be in the next release.
