### ISSUE TITLE
Please make the JsonApiMediaTypeConfiguration public

### ISSUE THREAD

**Issue by jimirocks** [toedter/spring-hateoas-jsonapi#8]
Currently the configuration class has package private visibility, which makes impossible to use it without spring-boot or in more advanced configurations (for example WebMvcTest not loading all the spring-boot stuff or the complex application combining more configurations together).

Yes, I know I could write my own configuration, but why to copy `JsonApiMediaTypeConfiguration`  only for the reason it's not public.

**Comment by toedter** [comment]
Hi Jiri, thanks for the request.

Actually I thought about making the `JsonApiMediaTypeConfiguration` public and we had a conversation about that in the Spring HATEOAS Gitter (see https://gitter.im/spring-projects/spring-hateoas)

The Spring HATEOAS team suggested to make it package-private, also the configurations of build-in media types are package-private. Since I want to be as close as possible to the build-in media types, I left it package-private.

Could you please be so kind and bring your point up in the Gitter group, I think it would be a good idea to provide the same visibility in all supported media types.

**Comment by gregturn** [comment]
@jimirocks Could you provide a use case where this becomes a problem?

**Comment by jimirocks** [comment]
@gregturn First, I need to say that I really appreciate the library is written with "private first" principle in mind. It's without any doubt good principle. But at the same time I believ I have valid usecase for making that class public, so let me express it in more detail:

1. Imagine application not built with spring-boot -  the `spring.factories` with content below is not applied
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
  com.toedter.spring.hateoas.jsonapi.JsonApiMediaTypeConfiguration
```
Then the only way now, is to duplicate the content of `JsonApiMediaTypeConfiguration` in the app's configuration class, but if it was public only `@Import` would be enough.

2. Similarly to the first case - imagine you want to write simple test not spawning all the spring context, just the MVC layer - that's what `@WebMvcTest` is made for!
```kotlin
@WebMvcTest
@ContextConfiguration(classes = [JsonApiMediaTypeConfiguration::class]) // compilation error here
class SomeMVCTest {
```

Above cases I struggle when trying to write library supporting the web layer (the goal is to unify the rest api layer among several components in the same product) based on hateoas + jsonapi

**Comment by gregturn** [comment]
I wouldn’t hitch things to Boot’s auto configuration property.  

I’d either A) create an Enable annotation that imports the class and requires people to manually add it to the app context or B) use Spring HATEOAS’s org.springframework.hateoas.config.MediaTypeConfigurationProvider property to make it unconditional.

This is probably good stuff to add to the reference docs. And it doesn’t require making anything public.

**Comment by jimirocks** [comment]
> I wouldn’t hitch things to Boot’s auto configuration property.
That's how it is currently made in this library...

Either A or B or both sounds like an acceptable and meaningful solution.

**Comment by ingogriebsch** [comment]
My two cents... :)

I will mark the configuration class as public in the first release of my Spring HATEOAS implementation (https://github.com/ingogriebsch/spring-hateoas-siren).

If someone is using the library in a Spring Boot environment they does not need to do anything but has otherwise the chance (and responsibility) to use the configuration class to initialize the library.

How the initialization will be handled in the future (either through an Annotation or another mechanism) is something that needs to be decided and also depends on the direction in which the Spring HATEOAS library is going.

**Comment by toedter** [comment]
Thanks for the discussion.
I guess I would go with Ingo's suggestion and make the configuration public for now.
I am currently on vacation and will probably not be able to make code changes in the next 2 weeks.

**Comment by odrotbohm** [comment]
Just for reference: the reason the configurations for the media types provided by Spring HATEOAS out of the box being package private is to make the `@EnableHypermediaSupport` annotation the sole way to activate those. Thus, external media type implementation can and should rather make those configuration files public if they're interested in being usable outside a Spring Boot context. I've filed [this ticket](https://github.com/spring-projects/spring-hateoas/issues/1364) to improve the reference documentation on this. As for `HalMediaTypeConfiguration` being public, I think this is a glitch that was overseen at some point.

We're going to revisit the configuration approach for consistency in 2.0 and will likely provide a mitigating 1.x release for smoother migration at some point.
